// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { AxisGridAPI } from './axisgrid-api'
import { AxisGrid, CopyAxisGridToAxisGridAPI } from './axisgrid'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { AxisAPI } from './axis-api'

@Injectable({
  providedIn: 'root'
})
export class AxisGridService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  AxisGridServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private axisgridsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.axisgridsUrl = origin + '/api/github.com/thomaspeugeot/phylotaxymusic/go/v1/axisgrids';
  }

  /** GET axisgrids from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisGridAPI[]> {
    return this.getAxisGrids(GONG__StackPath, frontRepo)
  }
  getAxisGrids(GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisGridAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<AxisGridAPI[]>(this.axisgridsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<AxisGridAPI[]>('getAxisGrids', []))
      );
  }

  /** GET axisgrid by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisGridAPI> {
    return this.getAxisGrid(id, GONG__StackPath, frontRepo)
  }
  getAxisGrid(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisGridAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.axisgridsUrl}/${id}`;
    return this.http.get<AxisGridAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched axisgrid id=${id}`)),
      catchError(this.handleError<AxisGridAPI>(`getAxisGrid id=${id}`))
    );
  }

  // postFront copy axisgrid to a version with encoded pointers and post to the back
  postFront(axisgrid: AxisGrid, GONG__StackPath: string): Observable<AxisGridAPI> {
    let axisgridAPI = new AxisGridAPI
    CopyAxisGridToAxisGridAPI(axisgrid, axisgridAPI)
    const id = typeof axisgridAPI === 'number' ? axisgridAPI : axisgridAPI.ID
    const url = `${this.axisgridsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<AxisGridAPI>(url, axisgridAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<AxisGridAPI>('postAxisGrid'))
    );
  }
  
  /** POST: add a new axisgrid to the server */
  post(axisgriddb: AxisGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisGridAPI> {
    return this.postAxisGrid(axisgriddb, GONG__StackPath, frontRepo)
  }
  postAxisGrid(axisgriddb: AxisGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisGridAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<AxisGridAPI>(this.axisgridsUrl, axisgriddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted axisgriddb id=${axisgriddb.ID}`)
      }),
      catchError(this.handleError<AxisGridAPI>('postAxisGrid'))
    );
  }

  /** DELETE: delete the axisgriddb from the server */
  delete(axisgriddb: AxisGridAPI | number, GONG__StackPath: string): Observable<AxisGridAPI> {
    return this.deleteAxisGrid(axisgriddb, GONG__StackPath)
  }
  deleteAxisGrid(axisgriddb: AxisGridAPI | number, GONG__StackPath: string): Observable<AxisGridAPI> {
    const id = typeof axisgriddb === 'number' ? axisgriddb : axisgriddb.ID;
    const url = `${this.axisgridsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<AxisGridAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted axisgriddb id=${id}`)),
      catchError(this.handleError<AxisGridAPI>('deleteAxisGrid'))
    );
  }

  // updateFront copy axisgrid to a version with encoded pointers and update to the back
  updateFront(axisgrid: AxisGrid, GONG__StackPath: string): Observable<AxisGridAPI> {
    let axisgridAPI = new AxisGridAPI
    CopyAxisGridToAxisGridAPI(axisgrid, axisgridAPI)
    const id = typeof axisgridAPI === 'number' ? axisgridAPI : axisgridAPI.ID
    const url = `${this.axisgridsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<AxisGridAPI>(url, axisgridAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<AxisGridAPI>('updateAxisGrid'))
    );
  }

  /** PUT: update the axisgriddb on the server */
  update(axisgriddb: AxisGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisGridAPI> {
    return this.updateAxisGrid(axisgriddb, GONG__StackPath, frontRepo)
  }
  updateAxisGrid(axisgriddb: AxisGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisGridAPI> {
    const id = typeof axisgriddb === 'number' ? axisgriddb : axisgriddb.ID;
    const url = `${this.axisgridsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<AxisGridAPI>(url, axisgriddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated axisgriddb id=${axisgriddb.ID}`)
      }),
      catchError(this.handleError<AxisGridAPI>('updateAxisGrid'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in AxisGridService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("AxisGridService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
