// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { CircleGridAPI } from './circlegrid-api'
import { CircleGrid, CopyCircleGridToCircleGridAPI } from './circlegrid'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { CircleAPI } from './circle-api'

@Injectable({
  providedIn: 'root'
})
export class CircleGridService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  CircleGridServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private circlegridsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.circlegridsUrl = origin + '/api/github.com/thomaspeugeot/phylotaxymusic/go/v1/circlegrids';
  }

  /** GET circlegrids from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<CircleGridAPI[]> {
    return this.getCircleGrids(GONG__StackPath, frontRepo)
  }
  getCircleGrids(GONG__StackPath: string, frontRepo: FrontRepo): Observable<CircleGridAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<CircleGridAPI[]>(this.circlegridsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<CircleGridAPI[]>('getCircleGrids', []))
      );
  }

  /** GET circlegrid by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CircleGridAPI> {
    return this.getCircleGrid(id, GONG__StackPath, frontRepo)
  }
  getCircleGrid(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CircleGridAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.circlegridsUrl}/${id}`;
    return this.http.get<CircleGridAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched circlegrid id=${id}`)),
      catchError(this.handleError<CircleGridAPI>(`getCircleGrid id=${id}`))
    );
  }

  // postFront copy circlegrid to a version with encoded pointers and post to the back
  postFront(circlegrid: CircleGrid, GONG__StackPath: string): Observable<CircleGridAPI> {
    let circlegridAPI = new CircleGridAPI
    CopyCircleGridToCircleGridAPI(circlegrid, circlegridAPI)
    const id = typeof circlegridAPI === 'number' ? circlegridAPI : circlegridAPI.ID
    const url = `${this.circlegridsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<CircleGridAPI>(url, circlegridAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<CircleGridAPI>('postCircleGrid'))
    );
  }
  
  /** POST: add a new circlegrid to the server */
  post(circlegriddb: CircleGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CircleGridAPI> {
    return this.postCircleGrid(circlegriddb, GONG__StackPath, frontRepo)
  }
  postCircleGrid(circlegriddb: CircleGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CircleGridAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<CircleGridAPI>(this.circlegridsUrl, circlegriddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted circlegriddb id=${circlegriddb.ID}`)
      }),
      catchError(this.handleError<CircleGridAPI>('postCircleGrid'))
    );
  }

  /** DELETE: delete the circlegriddb from the server */
  delete(circlegriddb: CircleGridAPI | number, GONG__StackPath: string): Observable<CircleGridAPI> {
    return this.deleteCircleGrid(circlegriddb, GONG__StackPath)
  }
  deleteCircleGrid(circlegriddb: CircleGridAPI | number, GONG__StackPath: string): Observable<CircleGridAPI> {
    const id = typeof circlegriddb === 'number' ? circlegriddb : circlegriddb.ID;
    const url = `${this.circlegridsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<CircleGridAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted circlegriddb id=${id}`)),
      catchError(this.handleError<CircleGridAPI>('deleteCircleGrid'))
    );
  }

  // updateFront copy circlegrid to a version with encoded pointers and update to the back
  updateFront(circlegrid: CircleGrid, GONG__StackPath: string): Observable<CircleGridAPI> {
    let circlegridAPI = new CircleGridAPI
    CopyCircleGridToCircleGridAPI(circlegrid, circlegridAPI)
    const id = typeof circlegridAPI === 'number' ? circlegridAPI : circlegridAPI.ID
    const url = `${this.circlegridsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<CircleGridAPI>(url, circlegridAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<CircleGridAPI>('updateCircleGrid'))
    );
  }

  /** PUT: update the circlegriddb on the server */
  update(circlegriddb: CircleGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CircleGridAPI> {
    return this.updateCircleGrid(circlegriddb, GONG__StackPath, frontRepo)
  }
  updateCircleGrid(circlegriddb: CircleGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CircleGridAPI> {
    const id = typeof circlegriddb === 'number' ? circlegriddb : circlegriddb.ID;
    const url = `${this.circlegridsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<CircleGridAPI>(url, circlegriddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated circlegriddb id=${circlegriddb.ID}`)
      }),
      catchError(this.handleError<CircleGridAPI>('updateCircleGrid'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in CircleGridService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("CircleGridService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
