// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { DiagramAPI } from './diagram-api'
import { Diagram, CopyDiagramToDiagramAPI } from './diagram'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class DiagramService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  DiagramServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private diagramsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.diagramsUrl = origin + '/api/github.com/thomaspeugeot/phylotaxymusic/go/v1/diagrams';
  }

  /** GET diagrams from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<DiagramAPI[]> {
    return this.getDiagrams(GONG__StackPath, frontRepo)
  }
  getDiagrams(GONG__StackPath: string, frontRepo: FrontRepo): Observable<DiagramAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<DiagramAPI[]>(this.diagramsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<DiagramAPI[]>('getDiagrams', []))
      );
  }

  /** GET diagram by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DiagramAPI> {
    return this.getDiagram(id, GONG__StackPath, frontRepo)
  }
  getDiagram(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DiagramAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.diagramsUrl}/${id}`;
    return this.http.get<DiagramAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched diagram id=${id}`)),
      catchError(this.handleError<DiagramAPI>(`getDiagram id=${id}`))
    );
  }

  // postFront copy diagram to a version with encoded pointers and post to the back
  postFront(diagram: Diagram, GONG__StackPath: string): Observable<DiagramAPI> {
    let diagramAPI = new DiagramAPI
    CopyDiagramToDiagramAPI(diagram, diagramAPI)
    const id = typeof diagramAPI === 'number' ? diagramAPI : diagramAPI.ID
    const url = `${this.diagramsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<DiagramAPI>(url, diagramAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<DiagramAPI>('postDiagram'))
    );
  }
  
  /** POST: add a new diagram to the server */
  post(diagramdb: DiagramAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DiagramAPI> {
    return this.postDiagram(diagramdb, GONG__StackPath, frontRepo)
  }
  postDiagram(diagramdb: DiagramAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DiagramAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<DiagramAPI>(this.diagramsUrl, diagramdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted diagramdb id=${diagramdb.ID}`)
      }),
      catchError(this.handleError<DiagramAPI>('postDiagram'))
    );
  }

  /** DELETE: delete the diagramdb from the server */
  delete(diagramdb: DiagramAPI | number, GONG__StackPath: string): Observable<DiagramAPI> {
    return this.deleteDiagram(diagramdb, GONG__StackPath)
  }
  deleteDiagram(diagramdb: DiagramAPI | number, GONG__StackPath: string): Observable<DiagramAPI> {
    const id = typeof diagramdb === 'number' ? diagramdb : diagramdb.ID;
    const url = `${this.diagramsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<DiagramAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted diagramdb id=${id}`)),
      catchError(this.handleError<DiagramAPI>('deleteDiagram'))
    );
  }

  // updateFront copy diagram to a version with encoded pointers and update to the back
  updateFront(diagram: Diagram, GONG__StackPath: string): Observable<DiagramAPI> {
    let diagramAPI = new DiagramAPI
    CopyDiagramToDiagramAPI(diagram, diagramAPI)
    const id = typeof diagramAPI === 'number' ? diagramAPI : diagramAPI.ID
    const url = `${this.diagramsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<DiagramAPI>(url, diagramAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<DiagramAPI>('updateDiagram'))
    );
  }

  /** PUT: update the diagramdb on the server */
  update(diagramdb: DiagramAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DiagramAPI> {
    return this.updateDiagram(diagramdb, GONG__StackPath, frontRepo)
  }
  updateDiagram(diagramdb: DiagramAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<DiagramAPI> {
    const id = typeof diagramdb === 'number' ? diagramdb : diagramdb.ID;
    const url = `${this.diagramsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<DiagramAPI>(url, diagramdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated diagramdb id=${diagramdb.ID}`)
      }),
      catchError(this.handleError<DiagramAPI>('updateDiagram'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in DiagramService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("DiagramService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
