// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { MovingLineAPI } from './movingline-api'
import { MovingLine, CopyMovingLineToMovingLineAPI } from './movingline'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { ShapeCategoryAPI } from './shapecategory-api'

@Injectable({
  providedIn: 'root'
})
export class MovingLineService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  MovingLineServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private movinglinesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.movinglinesUrl = origin + '/api/github.com/thomaspeugeot/phylotaxymusic/go/v1/movinglines';
  }

  /** GET movinglines from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<MovingLineAPI[]> {
    return this.getMovingLines(GONG__StackPath, frontRepo)
  }
  getMovingLines(GONG__StackPath: string, frontRepo: FrontRepo): Observable<MovingLineAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<MovingLineAPI[]>(this.movinglinesUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<MovingLineAPI[]>('getMovingLines', []))
      );
  }

  /** GET movingline by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<MovingLineAPI> {
    return this.getMovingLine(id, GONG__StackPath, frontRepo)
  }
  getMovingLine(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<MovingLineAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.movinglinesUrl}/${id}`;
    return this.http.get<MovingLineAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched movingline id=${id}`)),
      catchError(this.handleError<MovingLineAPI>(`getMovingLine id=${id}`))
    );
  }

  // postFront copy movingline to a version with encoded pointers and post to the back
  postFront(movingline: MovingLine, GONG__StackPath: string): Observable<MovingLineAPI> {
    let movinglineAPI = new MovingLineAPI
    CopyMovingLineToMovingLineAPI(movingline, movinglineAPI)
    const id = typeof movinglineAPI === 'number' ? movinglineAPI : movinglineAPI.ID
    const url = `${this.movinglinesUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<MovingLineAPI>(url, movinglineAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<MovingLineAPI>('postMovingLine'))
    );
  }
  
  /** POST: add a new movingline to the server */
  post(movinglinedb: MovingLineAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<MovingLineAPI> {
    return this.postMovingLine(movinglinedb, GONG__StackPath, frontRepo)
  }
  postMovingLine(movinglinedb: MovingLineAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<MovingLineAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<MovingLineAPI>(this.movinglinesUrl, movinglinedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted movinglinedb id=${movinglinedb.ID}`)
      }),
      catchError(this.handleError<MovingLineAPI>('postMovingLine'))
    );
  }

  /** DELETE: delete the movinglinedb from the server */
  delete(movinglinedb: MovingLineAPI | number, GONG__StackPath: string): Observable<MovingLineAPI> {
    return this.deleteMovingLine(movinglinedb, GONG__StackPath)
  }
  deleteMovingLine(movinglinedb: MovingLineAPI | number, GONG__StackPath: string): Observable<MovingLineAPI> {
    const id = typeof movinglinedb === 'number' ? movinglinedb : movinglinedb.ID;
    const url = `${this.movinglinesUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<MovingLineAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted movinglinedb id=${id}`)),
      catchError(this.handleError<MovingLineAPI>('deleteMovingLine'))
    );
  }

  // updateFront copy movingline to a version with encoded pointers and update to the back
  updateFront(movingline: MovingLine, GONG__StackPath: string): Observable<MovingLineAPI> {
    let movinglineAPI = new MovingLineAPI
    CopyMovingLineToMovingLineAPI(movingline, movinglineAPI)
    const id = typeof movinglineAPI === 'number' ? movinglineAPI : movinglineAPI.ID
    const url = `${this.movinglinesUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<MovingLineAPI>(url, movinglineAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<MovingLineAPI>('updateMovingLine'))
    );
  }

  /** PUT: update the movinglinedb on the server */
  update(movinglinedb: MovingLineAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<MovingLineAPI> {
    return this.updateMovingLine(movinglinedb, GONG__StackPath, frontRepo)
  }
  updateMovingLine(movinglinedb: MovingLineAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<MovingLineAPI> {
    const id = typeof movinglinedb === 'number' ? movinglinedb : movinglinedb.ID;
    const url = `${this.movinglinesUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<MovingLineAPI>(url, movinglinedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated movinglinedb id=${movinglinedb.ID}`)
      }),
      catchError(this.handleError<MovingLineAPI>('updateMovingLine'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in MovingLineService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("MovingLineService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
