// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { SpiralLineAPI } from './spiralline-api'
import { SpiralLine, CopySpiralLineToSpiralLineAPI } from './spiralline'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { ShapeCategoryAPI } from './shapecategory-api'

@Injectable({
  providedIn: 'root'
})
export class SpiralLineService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  SpiralLineServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private spirallinesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.spirallinesUrl = origin + '/api/github.com/thomaspeugeot/phylotaxymusic/go/v1/spirallines';
  }

  /** GET spirallines from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralLineAPI[]> {
    return this.getSpiralLines(GONG__StackPath, frontRepo)
  }
  getSpiralLines(GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralLineAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<SpiralLineAPI[]>(this.spirallinesUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<SpiralLineAPI[]>('getSpiralLines', []))
      );
  }

  /** GET spiralline by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralLineAPI> {
    return this.getSpiralLine(id, GONG__StackPath, frontRepo)
  }
  getSpiralLine(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralLineAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.spirallinesUrl}/${id}`;
    return this.http.get<SpiralLineAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched spiralline id=${id}`)),
      catchError(this.handleError<SpiralLineAPI>(`getSpiralLine id=${id}`))
    );
  }

  // postFront copy spiralline to a version with encoded pointers and post to the back
  postFront(spiralline: SpiralLine, GONG__StackPath: string): Observable<SpiralLineAPI> {
    let spirallineAPI = new SpiralLineAPI
    CopySpiralLineToSpiralLineAPI(spiralline, spirallineAPI)
    const id = typeof spirallineAPI === 'number' ? spirallineAPI : spirallineAPI.ID
    const url = `${this.spirallinesUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<SpiralLineAPI>(url, spirallineAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<SpiralLineAPI>('postSpiralLine'))
    );
  }
  
  /** POST: add a new spiralline to the server */
  post(spirallinedb: SpiralLineAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralLineAPI> {
    return this.postSpiralLine(spirallinedb, GONG__StackPath, frontRepo)
  }
  postSpiralLine(spirallinedb: SpiralLineAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralLineAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<SpiralLineAPI>(this.spirallinesUrl, spirallinedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted spirallinedb id=${spirallinedb.ID}`)
      }),
      catchError(this.handleError<SpiralLineAPI>('postSpiralLine'))
    );
  }

  /** DELETE: delete the spirallinedb from the server */
  delete(spirallinedb: SpiralLineAPI | number, GONG__StackPath: string): Observable<SpiralLineAPI> {
    return this.deleteSpiralLine(spirallinedb, GONG__StackPath)
  }
  deleteSpiralLine(spirallinedb: SpiralLineAPI | number, GONG__StackPath: string): Observable<SpiralLineAPI> {
    const id = typeof spirallinedb === 'number' ? spirallinedb : spirallinedb.ID;
    const url = `${this.spirallinesUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<SpiralLineAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted spirallinedb id=${id}`)),
      catchError(this.handleError<SpiralLineAPI>('deleteSpiralLine'))
    );
  }

  // updateFront copy spiralline to a version with encoded pointers and update to the back
  updateFront(spiralline: SpiralLine, GONG__StackPath: string): Observable<SpiralLineAPI> {
    let spirallineAPI = new SpiralLineAPI
    CopySpiralLineToSpiralLineAPI(spiralline, spirallineAPI)
    const id = typeof spirallineAPI === 'number' ? spirallineAPI : spirallineAPI.ID
    const url = `${this.spirallinesUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<SpiralLineAPI>(url, spirallineAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<SpiralLineAPI>('updateSpiralLine'))
    );
  }

  /** PUT: update the spirallinedb on the server */
  update(spirallinedb: SpiralLineAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralLineAPI> {
    return this.updateSpiralLine(spirallinedb, GONG__StackPath, frontRepo)
  }
  updateSpiralLine(spirallinedb: SpiralLineAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralLineAPI> {
    const id = typeof spirallinedb === 'number' ? spirallinedb : spirallinedb.ID;
    const url = `${this.spirallinesUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<SpiralLineAPI>(url, spirallinedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated spirallinedb id=${spirallinedb.ID}`)
      }),
      catchError(this.handleError<SpiralLineAPI>('updateSpiralLine'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in SpiralLineService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("SpiralLineService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
