// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { SpiralCircleGridAPI } from './spiralcirclegrid-api'
import { SpiralCircleGrid, CopySpiralCircleGridToSpiralCircleGridAPI } from './spiralcirclegrid'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { ShapeCategoryAPI } from './shapecategory-api'
import { SpiralRhombusGridAPI } from './spiralrhombusgrid-api'
import { SpiralCircleAPI } from './spiralcircle-api'

@Injectable({
  providedIn: 'root'
})
export class SpiralCircleGridService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  SpiralCircleGridServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private spiralcirclegridsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.spiralcirclegridsUrl = origin + '/api/github.com/thomaspeugeot/phylotaxymusic/go/v1/spiralcirclegrids';
  }

  /** GET spiralcirclegrids from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralCircleGridAPI[]> {
    return this.getSpiralCircleGrids(GONG__StackPath, frontRepo)
  }
  getSpiralCircleGrids(GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralCircleGridAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<SpiralCircleGridAPI[]>(this.spiralcirclegridsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<SpiralCircleGridAPI[]>('getSpiralCircleGrids', []))
      );
  }

  /** GET spiralcirclegrid by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralCircleGridAPI> {
    return this.getSpiralCircleGrid(id, GONG__StackPath, frontRepo)
  }
  getSpiralCircleGrid(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralCircleGridAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.spiralcirclegridsUrl}/${id}`;
    return this.http.get<SpiralCircleGridAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched spiralcirclegrid id=${id}`)),
      catchError(this.handleError<SpiralCircleGridAPI>(`getSpiralCircleGrid id=${id}`))
    );
  }

  // postFront copy spiralcirclegrid to a version with encoded pointers and post to the back
  postFront(spiralcirclegrid: SpiralCircleGrid, GONG__StackPath: string): Observable<SpiralCircleGridAPI> {
    let spiralcirclegridAPI = new SpiralCircleGridAPI
    CopySpiralCircleGridToSpiralCircleGridAPI(spiralcirclegrid, spiralcirclegridAPI)
    const id = typeof spiralcirclegridAPI === 'number' ? spiralcirclegridAPI : spiralcirclegridAPI.ID
    const url = `${this.spiralcirclegridsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<SpiralCircleGridAPI>(url, spiralcirclegridAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<SpiralCircleGridAPI>('postSpiralCircleGrid'))
    );
  }
  
  /** POST: add a new spiralcirclegrid to the server */
  post(spiralcirclegriddb: SpiralCircleGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralCircleGridAPI> {
    return this.postSpiralCircleGrid(spiralcirclegriddb, GONG__StackPath, frontRepo)
  }
  postSpiralCircleGrid(spiralcirclegriddb: SpiralCircleGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralCircleGridAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<SpiralCircleGridAPI>(this.spiralcirclegridsUrl, spiralcirclegriddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted spiralcirclegriddb id=${spiralcirclegriddb.ID}`)
      }),
      catchError(this.handleError<SpiralCircleGridAPI>('postSpiralCircleGrid'))
    );
  }

  /** DELETE: delete the spiralcirclegriddb from the server */
  delete(spiralcirclegriddb: SpiralCircleGridAPI | number, GONG__StackPath: string): Observable<SpiralCircleGridAPI> {
    return this.deleteSpiralCircleGrid(spiralcirclegriddb, GONG__StackPath)
  }
  deleteSpiralCircleGrid(spiralcirclegriddb: SpiralCircleGridAPI | number, GONG__StackPath: string): Observable<SpiralCircleGridAPI> {
    const id = typeof spiralcirclegriddb === 'number' ? spiralcirclegriddb : spiralcirclegriddb.ID;
    const url = `${this.spiralcirclegridsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<SpiralCircleGridAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted spiralcirclegriddb id=${id}`)),
      catchError(this.handleError<SpiralCircleGridAPI>('deleteSpiralCircleGrid'))
    );
  }

  // updateFront copy spiralcirclegrid to a version with encoded pointers and update to the back
  updateFront(spiralcirclegrid: SpiralCircleGrid, GONG__StackPath: string): Observable<SpiralCircleGridAPI> {
    let spiralcirclegridAPI = new SpiralCircleGridAPI
    CopySpiralCircleGridToSpiralCircleGridAPI(spiralcirclegrid, spiralcirclegridAPI)
    const id = typeof spiralcirclegridAPI === 'number' ? spiralcirclegridAPI : spiralcirclegridAPI.ID
    const url = `${this.spiralcirclegridsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<SpiralCircleGridAPI>(url, spiralcirclegridAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<SpiralCircleGridAPI>('updateSpiralCircleGrid'))
    );
  }

  /** PUT: update the spiralcirclegriddb on the server */
  update(spiralcirclegriddb: SpiralCircleGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralCircleGridAPI> {
    return this.updateSpiralCircleGrid(spiralcirclegriddb, GONG__StackPath, frontRepo)
  }
  updateSpiralCircleGrid(spiralcirclegriddb: SpiralCircleGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralCircleGridAPI> {
    const id = typeof spiralcirclegriddb === 'number' ? spiralcirclegriddb : spiralcirclegriddb.ID;
    const url = `${this.spiralcirclegridsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<SpiralCircleGridAPI>(url, spiralcirclegriddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated spiralcirclegriddb id=${spiralcirclegriddb.ID}`)
      }),
      catchError(this.handleError<SpiralCircleGridAPI>('updateSpiralCircleGrid'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in SpiralCircleGridService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("SpiralCircleGridService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
