// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { SpiralBezierGridAPI } from './spiralbeziergrid-api'
import { SpiralBezierGrid, CopySpiralBezierGridToSpiralBezierGridAPI } from './spiralbeziergrid'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { ShapeCategoryAPI } from './shapecategory-api'
import { SpiralBezierAPI } from './spiralbezier-api'

@Injectable({
  providedIn: 'root'
})
export class SpiralBezierGridService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  SpiralBezierGridServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private spiralbeziergridsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.spiralbeziergridsUrl = origin + '/api/github.com/thomaspeugeot/phylotaxymusic/go/v1/spiralbeziergrids';
  }

  /** GET spiralbeziergrids from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralBezierGridAPI[]> {
    return this.getSpiralBezierGrids(GONG__StackPath, frontRepo)
  }
  getSpiralBezierGrids(GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralBezierGridAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<SpiralBezierGridAPI[]>(this.spiralbeziergridsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<SpiralBezierGridAPI[]>('getSpiralBezierGrids', []))
      );
  }

  /** GET spiralbeziergrid by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralBezierGridAPI> {
    return this.getSpiralBezierGrid(id, GONG__StackPath, frontRepo)
  }
  getSpiralBezierGrid(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralBezierGridAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.spiralbeziergridsUrl}/${id}`;
    return this.http.get<SpiralBezierGridAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched spiralbeziergrid id=${id}`)),
      catchError(this.handleError<SpiralBezierGridAPI>(`getSpiralBezierGrid id=${id}`))
    );
  }

  // postFront copy spiralbeziergrid to a version with encoded pointers and post to the back
  postFront(spiralbeziergrid: SpiralBezierGrid, GONG__StackPath: string): Observable<SpiralBezierGridAPI> {
    let spiralbeziergridAPI = new SpiralBezierGridAPI
    CopySpiralBezierGridToSpiralBezierGridAPI(spiralbeziergrid, spiralbeziergridAPI)
    const id = typeof spiralbeziergridAPI === 'number' ? spiralbeziergridAPI : spiralbeziergridAPI.ID
    const url = `${this.spiralbeziergridsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<SpiralBezierGridAPI>(url, spiralbeziergridAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<SpiralBezierGridAPI>('postSpiralBezierGrid'))
    );
  }
  
  /** POST: add a new spiralbeziergrid to the server */
  post(spiralbeziergriddb: SpiralBezierGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralBezierGridAPI> {
    return this.postSpiralBezierGrid(spiralbeziergriddb, GONG__StackPath, frontRepo)
  }
  postSpiralBezierGrid(spiralbeziergriddb: SpiralBezierGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralBezierGridAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<SpiralBezierGridAPI>(this.spiralbeziergridsUrl, spiralbeziergriddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted spiralbeziergriddb id=${spiralbeziergriddb.ID}`)
      }),
      catchError(this.handleError<SpiralBezierGridAPI>('postSpiralBezierGrid'))
    );
  }

  /** DELETE: delete the spiralbeziergriddb from the server */
  delete(spiralbeziergriddb: SpiralBezierGridAPI | number, GONG__StackPath: string): Observable<SpiralBezierGridAPI> {
    return this.deleteSpiralBezierGrid(spiralbeziergriddb, GONG__StackPath)
  }
  deleteSpiralBezierGrid(spiralbeziergriddb: SpiralBezierGridAPI | number, GONG__StackPath: string): Observable<SpiralBezierGridAPI> {
    const id = typeof spiralbeziergriddb === 'number' ? spiralbeziergriddb : spiralbeziergriddb.ID;
    const url = `${this.spiralbeziergridsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<SpiralBezierGridAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted spiralbeziergriddb id=${id}`)),
      catchError(this.handleError<SpiralBezierGridAPI>('deleteSpiralBezierGrid'))
    );
  }

  // updateFront copy spiralbeziergrid to a version with encoded pointers and update to the back
  updateFront(spiralbeziergrid: SpiralBezierGrid, GONG__StackPath: string): Observable<SpiralBezierGridAPI> {
    let spiralbeziergridAPI = new SpiralBezierGridAPI
    CopySpiralBezierGridToSpiralBezierGridAPI(spiralbeziergrid, spiralbeziergridAPI)
    const id = typeof spiralbeziergridAPI === 'number' ? spiralbeziergridAPI : spiralbeziergridAPI.ID
    const url = `${this.spiralbeziergridsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<SpiralBezierGridAPI>(url, spiralbeziergridAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<SpiralBezierGridAPI>('updateSpiralBezierGrid'))
    );
  }

  /** PUT: update the spiralbeziergriddb on the server */
  update(spiralbeziergriddb: SpiralBezierGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralBezierGridAPI> {
    return this.updateSpiralBezierGrid(spiralbeziergriddb, GONG__StackPath, frontRepo)
  }
  updateSpiralBezierGrid(spiralbeziergriddb: SpiralBezierGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralBezierGridAPI> {
    const id = typeof spiralbeziergriddb === 'number' ? spiralbeziergriddb : spiralbeziergriddb.ID;
    const url = `${this.spiralbeziergridsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<SpiralBezierGridAPI>(url, spiralbeziergriddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated spiralbeziergriddb id=${spiralbeziergriddb.ID}`)
      }),
      catchError(this.handleError<SpiralBezierGridAPI>('updateSpiralBezierGrid'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in SpiralBezierGridService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("SpiralBezierGridService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
