// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { AxisAPI } from './axis-api'
import { Axis, CopyAxisToAxisAPI } from './axis'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { ShapeCategoryAPI } from './shapecategory-api'

@Injectable({
  providedIn: 'root'
})
export class AxisService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  AxisServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private axissUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.axissUrl = origin + '/api/github.com/thomaspeugeot/phyllotaxymusic/go/v1/axiss';
  }

  /** GET axiss from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisAPI[]> {
    return this.getAxiss(GONG__StackPath, frontRepo)
  }
  getAxiss(GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<AxisAPI[]>(this.axissUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<AxisAPI[]>('getAxiss', []))
      );
  }

  /** GET axis by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisAPI> {
    return this.getAxis(id, GONG__StackPath, frontRepo)
  }
  getAxis(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.axissUrl}/${id}`;
    return this.http.get<AxisAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched axis id=${id}`)),
      catchError(this.handleError<AxisAPI>(`getAxis id=${id}`))
    );
  }

  // postFront copy axis to a version with encoded pointers and post to the back
  postFront(axis: Axis, GONG__StackPath: string): Observable<AxisAPI> {
    let axisAPI = new AxisAPI
    CopyAxisToAxisAPI(axis, axisAPI)
    const id = typeof axisAPI === 'number' ? axisAPI : axisAPI.ID
    const url = `${this.axissUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<AxisAPI>(url, axisAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<AxisAPI>('postAxis'))
    );
  }
  
  /** POST: add a new axis to the server */
  post(axisdb: AxisAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisAPI> {
    return this.postAxis(axisdb, GONG__StackPath, frontRepo)
  }
  postAxis(axisdb: AxisAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<AxisAPI>(this.axissUrl, axisdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted axisdb id=${axisdb.ID}`)
      }),
      catchError(this.handleError<AxisAPI>('postAxis'))
    );
  }

  /** DELETE: delete the axisdb from the server */
  delete(axisdb: AxisAPI | number, GONG__StackPath: string): Observable<AxisAPI> {
    return this.deleteAxis(axisdb, GONG__StackPath)
  }
  deleteAxis(axisdb: AxisAPI | number, GONG__StackPath: string): Observable<AxisAPI> {
    const id = typeof axisdb === 'number' ? axisdb : axisdb.ID;
    const url = `${this.axissUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<AxisAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted axisdb id=${id}`)),
      catchError(this.handleError<AxisAPI>('deleteAxis'))
    );
  }

  // updateFront copy axis to a version with encoded pointers and update to the back
  updateFront(axis: Axis, GONG__StackPath: string): Observable<AxisAPI> {
    let axisAPI = new AxisAPI
    CopyAxisToAxisAPI(axis, axisAPI)
    const id = typeof axisAPI === 'number' ? axisAPI : axisAPI.ID
    const url = `${this.axissUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<AxisAPI>(url, axisAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<AxisAPI>('updateAxis'))
    );
  }

  /** PUT: update the axisdb on the server */
  update(axisdb: AxisAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisAPI> {
    return this.updateAxis(axisdb, GONG__StackPath, frontRepo)
  }
  updateAxis(axisdb: AxisAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<AxisAPI> {
    const id = typeof axisdb === 'number' ? axisdb : axisdb.ID;
    const url = `${this.axissUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<AxisAPI>(url, axisdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated axisdb id=${axisdb.ID}`)
      }),
      catchError(this.handleError<AxisAPI>('updateAxis'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in AxisService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("AxisService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
