// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { RhombusAPI } from './rhombus-api'
import { Rhombus, CopyRhombusToRhombusAPI } from './rhombus'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { ShapeCategoryAPI } from './shapecategory-api'

@Injectable({
  providedIn: 'root'
})
export class RhombusService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  RhombusServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private rhombussUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.rhombussUrl = origin + '/api/github.com/thomaspeugeot/phyllotaxymusic/go/v1/rhombuss';
  }

  /** GET rhombuss from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusAPI[]> {
    return this.getRhombuss(GONG__StackPath, frontRepo)
  }
  getRhombuss(GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<RhombusAPI[]>(this.rhombussUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<RhombusAPI[]>('getRhombuss', []))
      );
  }

  /** GET rhombus by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusAPI> {
    return this.getRhombus(id, GONG__StackPath, frontRepo)
  }
  getRhombus(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.rhombussUrl}/${id}`;
    return this.http.get<RhombusAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched rhombus id=${id}`)),
      catchError(this.handleError<RhombusAPI>(`getRhombus id=${id}`))
    );
  }

  // postFront copy rhombus to a version with encoded pointers and post to the back
  postFront(rhombus: Rhombus, GONG__StackPath: string): Observable<RhombusAPI> {
    let rhombusAPI = new RhombusAPI
    CopyRhombusToRhombusAPI(rhombus, rhombusAPI)
    const id = typeof rhombusAPI === 'number' ? rhombusAPI : rhombusAPI.ID
    const url = `${this.rhombussUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<RhombusAPI>(url, rhombusAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<RhombusAPI>('postRhombus'))
    );
  }

  /** POST: add a new rhombus to the server */
  post(rhombusdb: RhombusAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusAPI> {
    return this.postRhombus(rhombusdb, GONG__StackPath, frontRepo)
  }
  postRhombus(rhombusdb: RhombusAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<RhombusAPI>(this.rhombussUrl, rhombusdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted rhombusdb id=${rhombusdb.ID}`)
      }),
      catchError(this.handleError<RhombusAPI>('postRhombus'))
    );
  }

  /** DELETE: delete the rhombusdb from the server */
  delete(rhombusdb: RhombusAPI | number, GONG__StackPath: string): Observable<RhombusAPI> {
    return this.deleteRhombus(rhombusdb, GONG__StackPath)
  }
  deleteRhombus(rhombusdb: RhombusAPI | number, GONG__StackPath: string): Observable<RhombusAPI> {
    const id = typeof rhombusdb === 'number' ? rhombusdb : rhombusdb.ID;
    const url = `${this.rhombussUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<RhombusAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted rhombusdb id=${id}`)),
      catchError(this.handleError<RhombusAPI>('deleteRhombus'))
    );
  }

  // updateFront copy rhombus to a version with encoded pointers and update to the back
  updateFront(rhombus: Rhombus, GONG__StackPath: string): Observable<RhombusAPI> {
    let rhombusAPI = new RhombusAPI
    CopyRhombusToRhombusAPI(rhombus, rhombusAPI)
    const id = typeof rhombusAPI === 'number' ? rhombusAPI : rhombusAPI.ID
    const url = `${this.rhombussUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<RhombusAPI>(url, rhombusAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<RhombusAPI>('updateRhombus'))
    );
  }

  /** PUT: update the rhombusdb on the server */
  update(rhombusdb: RhombusAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusAPI> {
    return this.updateRhombus(rhombusdb, GONG__StackPath, frontRepo)
  }
  updateRhombus(rhombusdb: RhombusAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusAPI> {
    const id = typeof rhombusdb === 'number' ? rhombusdb : rhombusdb.ID;
    const url = `${this.rhombussUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<RhombusAPI>(url, rhombusdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated rhombusdb id=${rhombusdb.ID}`)
      }),
      catchError(this.handleError<RhombusAPI>('updateRhombus'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in RhombusService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("RhombusService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
