// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { RhombusGridAPI } from './rhombusgrid-api'
import { RhombusGrid, CopyRhombusGridToRhombusGridAPI } from './rhombusgrid'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { RhombusAPI } from './rhombus-api'
import { ShapeCategoryAPI } from './shapecategory-api'

@Injectable({
  providedIn: 'root'
})
export class RhombusGridService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  RhombusGridServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private rhombusgridsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.rhombusgridsUrl = origin + '/api/github.com/thomaspeugeot/phyllotaxymusic/go/v1/rhombusgrids';
  }

  /** GET rhombusgrids from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusGridAPI[]> {
    return this.getRhombusGrids(GONG__StackPath, frontRepo)
  }
  getRhombusGrids(GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusGridAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<RhombusGridAPI[]>(this.rhombusgridsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<RhombusGridAPI[]>('getRhombusGrids', []))
      );
  }

  /** GET rhombusgrid by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusGridAPI> {
    return this.getRhombusGrid(id, GONG__StackPath, frontRepo)
  }
  getRhombusGrid(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusGridAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.rhombusgridsUrl}/${id}`;
    return this.http.get<RhombusGridAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched rhombusgrid id=${id}`)),
      catchError(this.handleError<RhombusGridAPI>(`getRhombusGrid id=${id}`))
    );
  }

  // postFront copy rhombusgrid to a version with encoded pointers and post to the back
  postFront(rhombusgrid: RhombusGrid, GONG__StackPath: string): Observable<RhombusGridAPI> {
    let rhombusgridAPI = new RhombusGridAPI
    CopyRhombusGridToRhombusGridAPI(rhombusgrid, rhombusgridAPI)
    const id = typeof rhombusgridAPI === 'number' ? rhombusgridAPI : rhombusgridAPI.ID
    const url = `${this.rhombusgridsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<RhombusGridAPI>(url, rhombusgridAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<RhombusGridAPI>('postRhombusGrid'))
    );
  }
  
  /** POST: add a new rhombusgrid to the server */
  post(rhombusgriddb: RhombusGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusGridAPI> {
    return this.postRhombusGrid(rhombusgriddb, GONG__StackPath, frontRepo)
  }
  postRhombusGrid(rhombusgriddb: RhombusGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusGridAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<RhombusGridAPI>(this.rhombusgridsUrl, rhombusgriddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted rhombusgriddb id=${rhombusgriddb.ID}`)
      }),
      catchError(this.handleError<RhombusGridAPI>('postRhombusGrid'))
    );
  }

  /** DELETE: delete the rhombusgriddb from the server */
  delete(rhombusgriddb: RhombusGridAPI | number, GONG__StackPath: string): Observable<RhombusGridAPI> {
    return this.deleteRhombusGrid(rhombusgriddb, GONG__StackPath)
  }
  deleteRhombusGrid(rhombusgriddb: RhombusGridAPI | number, GONG__StackPath: string): Observable<RhombusGridAPI> {
    const id = typeof rhombusgriddb === 'number' ? rhombusgriddb : rhombusgriddb.ID;
    const url = `${this.rhombusgridsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<RhombusGridAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted rhombusgriddb id=${id}`)),
      catchError(this.handleError<RhombusGridAPI>('deleteRhombusGrid'))
    );
  }

  // updateFront copy rhombusgrid to a version with encoded pointers and update to the back
  updateFront(rhombusgrid: RhombusGrid, GONG__StackPath: string): Observable<RhombusGridAPI> {
    let rhombusgridAPI = new RhombusGridAPI
    CopyRhombusGridToRhombusGridAPI(rhombusgrid, rhombusgridAPI)
    const id = typeof rhombusgridAPI === 'number' ? rhombusgridAPI : rhombusgridAPI.ID
    const url = `${this.rhombusgridsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<RhombusGridAPI>(url, rhombusgridAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<RhombusGridAPI>('updateRhombusGrid'))
    );
  }

  /** PUT: update the rhombusgriddb on the server */
  update(rhombusgriddb: RhombusGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusGridAPI> {
    return this.updateRhombusGrid(rhombusgriddb, GONG__StackPath, frontRepo)
  }
  updateRhombusGrid(rhombusgriddb: RhombusGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<RhombusGridAPI> {
    const id = typeof rhombusgriddb === 'number' ? rhombusgriddb : rhombusgriddb.ID;
    const url = `${this.rhombusgridsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<RhombusGridAPI>(url, rhombusgriddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated rhombusgriddb id=${rhombusgriddb.ID}`)
      }),
      catchError(this.handleError<RhombusGridAPI>('updateRhombusGrid'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in RhombusGridService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("RhombusGridService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
