// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { SpiralRhombusGridAPI } from './spiralrhombusgrid-api'
import { SpiralRhombusGrid, CopySpiralRhombusGridToSpiralRhombusGridAPI } from './spiralrhombusgrid'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { ShapeCategoryAPI } from './shapecategory-api'
import { SpiralRhombusAPI } from './spiralrhombus-api'

@Injectable({
  providedIn: 'root'
})
export class SpiralRhombusGridService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  SpiralRhombusGridServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private spiralrhombusgridsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.spiralrhombusgridsUrl = origin + '/api/github.com/thomaspeugeot/phylotaxymusic/go/v1/spiralrhombusgrids';
  }

  /** GET spiralrhombusgrids from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralRhombusGridAPI[]> {
    return this.getSpiralRhombusGrids(GONG__StackPath, frontRepo)
  }
  getSpiralRhombusGrids(GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralRhombusGridAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<SpiralRhombusGridAPI[]>(this.spiralrhombusgridsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<SpiralRhombusGridAPI[]>('getSpiralRhombusGrids', []))
      );
  }

  /** GET spiralrhombusgrid by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralRhombusGridAPI> {
    return this.getSpiralRhombusGrid(id, GONG__StackPath, frontRepo)
  }
  getSpiralRhombusGrid(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralRhombusGridAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.spiralrhombusgridsUrl}/${id}`;
    return this.http.get<SpiralRhombusGridAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched spiralrhombusgrid id=${id}`)),
      catchError(this.handleError<SpiralRhombusGridAPI>(`getSpiralRhombusGrid id=${id}`))
    );
  }

  // postFront copy spiralrhombusgrid to a version with encoded pointers and post to the back
  postFront(spiralrhombusgrid: SpiralRhombusGrid, GONG__StackPath: string): Observable<SpiralRhombusGridAPI> {
    let spiralrhombusgridAPI = new SpiralRhombusGridAPI
    CopySpiralRhombusGridToSpiralRhombusGridAPI(spiralrhombusgrid, spiralrhombusgridAPI)
    const id = typeof spiralrhombusgridAPI === 'number' ? spiralrhombusgridAPI : spiralrhombusgridAPI.ID
    const url = `${this.spiralrhombusgridsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<SpiralRhombusGridAPI>(url, spiralrhombusgridAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<SpiralRhombusGridAPI>('postSpiralRhombusGrid'))
    );
  }
  
  /** POST: add a new spiralrhombusgrid to the server */
  post(spiralrhombusgriddb: SpiralRhombusGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralRhombusGridAPI> {
    return this.postSpiralRhombusGrid(spiralrhombusgriddb, GONG__StackPath, frontRepo)
  }
  postSpiralRhombusGrid(spiralrhombusgriddb: SpiralRhombusGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralRhombusGridAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<SpiralRhombusGridAPI>(this.spiralrhombusgridsUrl, spiralrhombusgriddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted spiralrhombusgriddb id=${spiralrhombusgriddb.ID}`)
      }),
      catchError(this.handleError<SpiralRhombusGridAPI>('postSpiralRhombusGrid'))
    );
  }

  /** DELETE: delete the spiralrhombusgriddb from the server */
  delete(spiralrhombusgriddb: SpiralRhombusGridAPI | number, GONG__StackPath: string): Observable<SpiralRhombusGridAPI> {
    return this.deleteSpiralRhombusGrid(spiralrhombusgriddb, GONG__StackPath)
  }
  deleteSpiralRhombusGrid(spiralrhombusgriddb: SpiralRhombusGridAPI | number, GONG__StackPath: string): Observable<SpiralRhombusGridAPI> {
    const id = typeof spiralrhombusgriddb === 'number' ? spiralrhombusgriddb : spiralrhombusgriddb.ID;
    const url = `${this.spiralrhombusgridsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<SpiralRhombusGridAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted spiralrhombusgriddb id=${id}`)),
      catchError(this.handleError<SpiralRhombusGridAPI>('deleteSpiralRhombusGrid'))
    );
  }

  // updateFront copy spiralrhombusgrid to a version with encoded pointers and update to the back
  updateFront(spiralrhombusgrid: SpiralRhombusGrid, GONG__StackPath: string): Observable<SpiralRhombusGridAPI> {
    let spiralrhombusgridAPI = new SpiralRhombusGridAPI
    CopySpiralRhombusGridToSpiralRhombusGridAPI(spiralrhombusgrid, spiralrhombusgridAPI)
    const id = typeof spiralrhombusgridAPI === 'number' ? spiralrhombusgridAPI : spiralrhombusgridAPI.ID
    const url = `${this.spiralrhombusgridsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<SpiralRhombusGridAPI>(url, spiralrhombusgridAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<SpiralRhombusGridAPI>('updateSpiralRhombusGrid'))
    );
  }

  /** PUT: update the spiralrhombusgriddb on the server */
  update(spiralrhombusgriddb: SpiralRhombusGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralRhombusGridAPI> {
    return this.updateSpiralRhombusGrid(spiralrhombusgriddb, GONG__StackPath, frontRepo)
  }
  updateSpiralRhombusGrid(spiralrhombusgriddb: SpiralRhombusGridAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<SpiralRhombusGridAPI> {
    const id = typeof spiralrhombusgriddb === 'number' ? spiralrhombusgriddb : spiralrhombusgriddb.ID;
    const url = `${this.spiralrhombusgridsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<SpiralRhombusGridAPI>(url, spiralrhombusgriddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated spiralrhombusgriddb id=${spiralrhombusgriddb.ID}`)
      }),
      catchError(this.handleError<SpiralRhombusGridAPI>('updateSpiralRhombusGrid'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in SpiralRhombusGridService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("SpiralRhombusGridService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
